name: RandomGen Tests and Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage
        pip install -e .
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coverage report
        coverage xml
        
    - name: Check coverage threshold
      if: github.event_name == 'pull_request'
      run: |
        # Extract coverage percentage for src directory
        SRC_COVERAGE=$(coverage report --include="src/*" | grep TOTAL | awk '{print $4}' | sed 's/%//')
        echo "Source code coverage: $SRC_COVERAGE%"
        
        # Check if coverage is below threshold
        if (( $(echo "$SRC_COVERAGE < 95" | bc -l) )); then
          echo "Error: Code coverage for src directory is below the required 95%. Current coverage: $SRC_COVERAGE%"
          exit 1
        fi
        echo "Coverage threshold met: $SRC_COVERAGE% ✅"
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
